### ISSUE TITLE
Join Welcome and Sources tab

### ISSUE THREAD

**Issue by itaiperi** [Arieg419/Mindflow.ai#8]
Remove sources tab, and instead, in opening screen (the 'Welcome' tab), have the choice of opening an existing project, Opening a new project, starting a timeline from scratch (and maybe the first and second option should be together, since they both rely on git. We should just say 'Open project', and if there's a .mf folder then load whatever has been done in the past, otherwise - new timeline. And we need to specify the fact that it works only with git right now.)

**Comment by Arieg419** [comment]
Merged both views
